"""Repository protocols (TR-21) and the UnitOfWork contract (TR-23).

Concrete implementations live in `app/repositories/` (SQLAlchemy) and
`tests/fakes/` (in-memory) — both must satisfy these Protocols. Services
type-hint against these names, never against concretes.

Conventions:

- One protocol per aggregate (design 11A.1). Variant + InventoryLevel are
  inside the Product / Inventory aggregates respectively, so they are not
  separate repositories.
- Read methods return frozen domain dataclasses or `Page[T]` for paginated
  results.
- Write methods (`upsert`) take a domain object and have no return value;
  inserts populate the autogenerated PK on the returned-from-DB equivalent
  but services rarely care — they re-read if they need the assigned id.
- Composite filters use a Spec (`OrderSpec`, …) instead of a long kwarg list.
- Pagination uses opaque cursors. Encoding is a repo-internal detail.
"""

from __future__ import annotations

from datetime import date, datetime
from types import TracebackType
from typing import Protocol, runtime_checkable

from app.domain.enums import FinancialStatus, SyncResource
from app.domain.models import (
    AnalyticsKpiDay,
    ApiAuditLogEntry,
    ApiToken,
    ApiTokenId,
    Customer,
    CustomerId,
    InventoryItem,
    InventoryLevel,
    Location,
    LocationId,
    Order,
    OrderId,
    Page,
    Product,
    ProductId,
    SessionsDay,
    Store,
    StoreId,
    SubscriptionContract,
    SubscriptionContractId,
    SyncStateRow,
    VariantId,
)
from app.domain.specs import (
    AnalyticsWindowSpec,
    InventorySpec,
    OrderSpec,
    ProductSpec,
    SubscriptionSpec,
)

# ---------------------------------------------------------------------------
# Aggregate repositories
# ---------------------------------------------------------------------------


@runtime_checkable
class StoreRepository(Protocol):
    def list_active(self) -> tuple[Store, ...]: ...

    def get(self, store_id: StoreId) -> Store | None: ...

    def get_by_key(self, store_key: str) -> Store | None: ...

    def get_by_domain(self, shop_domain: str) -> Store | None: ...

    def upsert(self, store: Store) -> None: ...


@runtime_checkable
class LocationRepository(Protocol):
    def list_for_store(self, store_id: StoreId) -> tuple[Location, ...]: ...

    def get(self, location_id: LocationId) -> Location | None: ...

    def get_by_gid(self, store_id: StoreId, gid: str) -> Location | None: ...

    def upsert(self, location: Location) -> None: ...


@runtime_checkable
class CustomerRepository(Protocol):
    def get(self, customer_id: CustomerId) -> Customer | None: ...

    def get_by_gid(self, store_id: StoreId, gid: str) -> Customer | None: ...

    def get_by_email(self, store_id: StoreId, email: str) -> Customer | None: ...

    def upsert(self, customer: Customer) -> None: ...


@runtime_checkable
class OrderRepository(Protocol):
    """Order aggregate: includes line items, shipping address, fulfillments."""

    def get(self, order_id: OrderId) -> Order | None: ...

    def get_by_gid(self, store_id: StoreId, gid: str) -> Order | None: ...

    def find(
        self,
        spec: OrderSpec,
        *,
        limit: int = 50,
        cursor: str | None = None,
    ) -> Page[Order]: ...

    def count_by_status(
        self,
        store_id: StoreId,
        since: datetime,
        until: datetime,
    ) -> dict[FinancialStatus, int]: ...

    def upsert(self, order: Order) -> None: ...


@runtime_checkable
class ProductRepository(Protocol):
    """Product aggregate: includes variants."""

    def get(self, product_id: ProductId) -> Product | None: ...

    def get_by_gid(self, store_id: StoreId, gid: str) -> Product | None: ...

    def get_by_handle(self, store_id: StoreId, handle: str) -> Product | None: ...

    def find(
        self,
        spec: ProductSpec,
        *,
        limit: int = 50,
        cursor: str | None = None,
    ) -> Page[Product]: ...

    def variant_gid_map(self, store_id: StoreId) -> dict[str, VariantId]:
        """Return {variant_gid: variant_id} for every variant of every product
        in the store. Used by inventory sync to resolve FKs in one batch."""
        ...

    def product_gid_map(self, store_id: StoreId) -> dict[str, ProductId]:
        """Return {product_gid: product_id} for every product in the store.
        Used by orders sync to resolve OrderLineItem.product_id FKs in batch."""
        ...

    def upsert(self, product: Product) -> None: ...


@runtime_checkable
class InventoryRepository(Protocol):
    """InventoryItem aggregate: items + their levels at every location."""

    def list_levels(
        self,
        spec: InventorySpec,
        *,
        limit: int = 50,
        cursor: str | None = None,
    ) -> Page[InventoryLevel]: ...

    def get_item(self, store_id: StoreId, gid: str) -> InventoryItem | None: ...

    def list_low_stock(
        self,
        store_id: StoreId,
        threshold: int,
        *,
        limit: int = 50,
    ) -> tuple[InventoryLevel, ...]: ...

    def upsert_item(self, item: InventoryItem) -> None: ...

    def upsert_level(self, level: InventoryLevel) -> None: ...


@runtime_checkable
class SubscriptionRepository(Protocol):
    def get(self, contract_id: SubscriptionContractId) -> SubscriptionContract | None: ...

    def find(
        self,
        spec: SubscriptionSpec,
        *,
        limit: int = 50,
        cursor: str | None = None,
    ) -> Page[SubscriptionContract]: ...

    def upsert(self, contract: SubscriptionContract) -> None: ...


@runtime_checkable
class AnalyticsRepository(Protocol):
    def get_sessions_day(self, store_id: StoreId, day: date) -> SessionsDay | None: ...

    def upsert_sessions_day(self, row: SessionsDay) -> None: ...

    def list_sessions(self, spec: AnalyticsWindowSpec) -> tuple[SessionsDay, ...]: ...

    def get_kpi_day(self, store_id: StoreId, day: date) -> AnalyticsKpiDay | None: ...

    def upsert_kpi_day(self, row: AnalyticsKpiDay) -> None: ...

    def list_kpis(self, spec: AnalyticsWindowSpec) -> tuple[AnalyticsKpiDay, ...]: ...


@runtime_checkable
class SyncStateRepository(Protocol):
    def get(self, store_id: StoreId, resource: SyncResource) -> SyncStateRow | None: ...

    def list_for_store(self, store_id: StoreId) -> tuple[SyncStateRow, ...]: ...

    def upsert(self, row: SyncStateRow) -> None: ...


@runtime_checkable
class ApiTokenRepository(Protocol):
    """Bearer-token store (TR-4). Hashes are SHA-256 hex digests."""

    def get_by_hash(self, token_hash: str) -> ApiToken | None: ...

    def list_active(self) -> tuple[ApiToken, ...]: ...

    def upsert(self, token: ApiToken) -> ApiTokenId:
        """Insert or update; return the persisted id (newly assigned on insert)."""
        ...

    def touch_last_used(self, token_id: ApiTokenId, when: datetime) -> None: ...

    def revoke(self, token_id: ApiTokenId, when: datetime) -> None: ...


@runtime_checkable
class ApiAuditLogRepository(Protocol):
    """Append-only audit log (TR-6)."""

    def record(self, entry: ApiAuditLogEntry) -> None: ...

    def list_recent(self, *, limit: int = 100) -> tuple[ApiAuditLogEntry, ...]: ...


@runtime_checkable
class WebhookEventLogRepository(Protocol):
    """Operational log of every webhook delivery (TR-14).

    Reads (`get_for_processing`) exist for the worker dispatch path; status
    updates (`mark_processed` / `mark_failed`) close the loop on each row.
    """

    def record(  # noqa: PLR0913 — kwargs-only by design
        self,
        *,
        store_id: StoreId,
        topic: str,
        shopify_webhook_id: str | None,
        received_at: datetime,
        hmac_valid: bool,
        raw_body: bytes,
    ) -> int: ...

    def get_for_processing(self, event_id: int) -> tuple[StoreId, str, bytes] | None: ...

    """Return (store_id, topic, decompressed_raw_body) for the row, or None
    if it doesn't exist or is already processed."""

    def mark_processed(self, event_id: int) -> None: ...

    def mark_failed(self, event_id: int, error: str) -> None: ...


# ---------------------------------------------------------------------------
# Unit of Work (TR-23)
# ---------------------------------------------------------------------------


@runtime_checkable
class UnitOfWork(Protocol):
    """Per-request transactional boundary.

    Services do all repository work inside `with uow_factory() as uow: ...`.
    Commit and rollback are explicit — the context manager only auto-rollbacks
    on uncaught exception.
    """

    stores: StoreRepository
    locations: LocationRepository
    customers: CustomerRepository
    orders: OrderRepository
    products: ProductRepository
    inventory: InventoryRepository
    subscriptions: SubscriptionRepository
    analytics: AnalyticsRepository
    sync_state: SyncStateRepository
    webhook_events: WebhookEventLogRepository
    api_tokens: ApiTokenRepository
    api_audit_log: ApiAuditLogRepository

    def __enter__(self) -> UnitOfWork: ...

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
